---
namespace: trippsc2
name: nexus
version: 1.1.0
readme: README.md
authors:
  - Jim Tarpley (@trippsc2)
description: This collection contains modules and roles for configuring Nexus Repository Manager.

license_file: 'LICENSE'

tags:
  - infrastructure
  - linux

dependencies:
  ansible.posix: '>=1.0.1'
  community.general: '>=1.0.0'
  trippsc2.general: '>=2.6.0'

repository: https://github.com/trippsoft/ansible-collection-nexus.git

manifest:
  directives:
    - recursive-include roles/* *.md
    - recursive-include roles/*/files **
    - exclude galaxy.yml galaxy.yaml MANIFEST.json FILES.json *.tar.gz
    - recursive-exclude tests/output **
    - recursive-exclude roles/*/molecule **
    - recursive-exclude molecule **
    - global-exclude /.* /__pycache__
